name: Build Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  py-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install '.[docs]'
      - name: Build docs
        run: |
          cd python/docs
          make html
      - name: Make output directory
        run: mkdir -p _artifacts
      - name: Compress docs
        run: |
          cd python/docs/_build/html
          tar -czf ../../../../_artifacts/docs.tar.gz .
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: python-docs.tar.gz
          path: _artifacts/docs.tar.gz
